# Generated by Django 2.0.7 on 2021-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='', max_length=60)),
                ('LastName', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.EmailField(blank=True, default='', max_length=60)),
                ('Username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
