# Generated by Django 2.0.7 on 2021-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Miss', 'Miss.'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.')], default='', max_length=60),
        ),
    ]
