# Generated by Django 2.0.7 on 2021-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20210615_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('', ''), ('Miss', 'Miss.')], default='', max_length=60),
        ),
    ]
