# Generated by Django 2.0.7 on 2021-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20210615_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('', ''), ('Miss', 'Miss.')], default='--', max_length=60),
        ),
    ]
