# Generated by Django 2.0.7 on 2021-06-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_auto_20210615_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Miss', 'Miss.'), ('Mrs.', 'Mrs.'), ('', ''), ('Mr.', 'Mr.')], default='--', max_length=60, null=True),
        ),
    ]
