# Generated by Django 2.0.7 on 2021-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0009_auto_20210615_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Miss', 'Miss.'), ('', ''), ('Mr.', 'Mr.')], default='', max_length=60),
        ),
    ]
