# Generated by Django 3.2.4 on 2021-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_auto_20210615_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('', ''), ('Miss', 'Miss.'), ('Dr.', 'Dr.')], default='', max_length=60),
        ),
    ]
