# Generated by Django 3.2.4 on 2021-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss.'), ('Mr.', 'Mr.')], default='', max_length=60),
        ),
    ]
