# Generated by Django 3.2.4 on 2021-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0018_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr.', 'Mr.'), ('Miss', 'Miss.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='', max_length=60),
        ),
    ]
